## Muhammad Muzammil
25 September 2024
##### **Numpy Practice**

In [58]:
import numpy as np

### **One Dimensional Array**

In [59]:
new = np.array([1,2,3,4,5])
new

array([1, 2, 3, 4, 5])

### **Two Dimensional Array**

In [60]:
data = np.array([  [1,2,3] , [2,4,6] ])
data

array([[1, 2, 3],
       [2, 4, 6]])

### Replacing value from an array

In [61]:
new[0] = 12
new

array([12,  2,  3,  4,  5])

## Array Attributes

### Number of dimensions of an array

In [62]:
data.ndim

2

### **Rows and Columns of array**

In [63]:
data.shape

(2, 3)

### **Size of Array (Number of values in array)**

In [64]:
data.size

6

### **Data type of Array**

In [65]:
data.dtype

dtype('int64')

### **Array Operations**

#### Adding Arrays

In [66]:
ar1 = np.array([5,6,7,8])
ar2 = np.array([1,3,5,6])

result = ar1 + ar2
result

array([ 6,  9, 12, 14])

### Multiplying Array

In [67]:
np.dot(ar1, ar2)

np.int64(106)

#  slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()

### Indexing

In [68]:
ar1[0]

np.int64(5)

### Slicing

In [69]:
ar1[1:3]

array([6, 7])

##### VStack (Vertical Stack)

In [70]:
aa = np.array([[1, 1],
               [2, 2]])

bb = np.array([[3, 3],
               [4, 4]])

np.vstack((aa, bb))



array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

##### hStack (Horizontal Stack)

In [71]:
np.hstack((aa, bb))


array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

##### hSplit (Spliting an Array)

In [72]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [73]:
np.hsplit(x, 4)


[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

### Broadcasting
There are times when you might want to carry out an operation between an array and a single number

In [74]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

### Condition

In [75]:
k = np.array([[1 , 2, 3, 4], [2, 6, 4, 8], [9, 10, 11, 12]])
print(k[k < 5])


[1 2 3 4 2 4]


In [76]:
print(k[k%2 == 0])

[ 2  4  2  6  4  8 10 12]


In [77]:
print(k[(k>2) & (k < 8)])

[3 4 6 4]


### Special Arrays (Creating array by giving zero)

In [78]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### Special Arrays (Creating array by giving Ones)

In [79]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### Create an empty array with 2 elements

In [80]:
np.empty(2)

array([1.6, 3.2])

### An array with a range of elements

In [81]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### An array that contains a range of evenly spaced intervals

In [82]:
np.arange(2, 9, 2)


array([2, 4, 6, 8])

### To create an array with values that are spaced linearly in a specified interval:

In [83]:
np.linspace(5, 15, num=5)

array([ 5. ,  7.5, 10. , 12.5, 15. ])

### Specifying your data type



In [84]:
x = np.ones(3, dtype=np.int64)
x

array([1, 1, 1])

### Special Arrays (Creating array by giving eye (eye means diagonally) )

In [85]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Random

In [86]:
np.random.rand(2,4)

array([[0.00664645, 0.7385921 , 0.12258776, 0.04525024],
       [0.05590074, 0.31981722, 0.27043844, 0.14873018]])

### Sum of Array

In [87]:
np.sum(ar1)

np.int64(26)

### Sorting Array

In [88]:
a = np.array([7,9,6,8])

np.sort(a)

array([6, 7, 8, 9])

### Concatenate

In [89]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6, 7, 8])

### ReShaping an Array

In [90]:
x1 = np.array([0,1,2,3,4,5,6,7,8,9])
z = x1.reshape(5,2)
z

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### Transpose of Array

In [97]:
z.transpose()

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

### Mean of Array

In [91]:
np.mean(ar1)

np.float64(6.5)

### Median of Array

In [92]:
np.median(ar1)

np.float64(6.5)

###  Min & Max of Array

In [93]:
np.max(ar1)

np.int64(8)

In [94]:
np.min(ar1)

np.int64(5)

### Standard Deviation

In [95]:
np.std(ar1)

np.float64(1.118033988749895)

### Reversing an array

> Reversing 1D Array

In [99]:
rev = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(rev)

reversed_arr

array([8, 7, 6, 5, 4, 3, 2, 1])

> Reversing 2D Array

In [100]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
reversed_arr

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

### Flattening multidimensional arrays

In [101]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])