## **Muhammad Muzammil**

Numpy Scenario Assignment

____________________________________________________________________________________________________________________


Q1. Sales Data Analysis: You have a NumPy array representing the daily sales of a product over a month. Each element in the array represents the sales for a particular day. Compute the total sales, average sales, and the day with the highest sales.


In [2]:
import numpy as np

data = np.random.randint(20,50,30)

reshaped_data = data.reshape(30,1)
reshaped_data

array([[44],
       [28],
       [26],
       [42],
       [30],
       [47],
       [43],
       [23],
       [37],
       [27],
       [48],
       [46],
       [21],
       [23],
       [46],
       [44],
       [44],
       [40],
       [26],
       [21],
       [36],
       [34],
       [31],
       [35],
       [44],
       [33],
       [28],
       [47],
       [32],
       [27]], dtype=int32)

In [3]:
#Total Sales

sales = np.sum(reshaped_data)
print("Total Sales over 30 Days are ",sales )

Total Sales over 30 Days are  1053


In [4]:
#Average Sales

Avg_sales = np.mean(reshaped_data)
print("Average Sales of Data over 30 Days are ", Avg_sales)

Average Sales of Data over 30 Days are  35.1


In [5]:
#Highest Sales Day

Highest_Sale = np.max(reshaped_data)

day = np.argmax(reshaped_data) + 1
print(f"The day {day} had highest number of sales which were {Highest_Sale}")


The day 11 had highest number of sales which were 48


Q2. Weather Data Processing: Given a 2D NumPy array where each row represents daily temperature readings for a week (7 days), find the average temperature for each day across all weeks.


In [6]:
#7 Days Temperature Data three readings each day
data = np.random.randint(20,40,(7,3))
data

array([[35, 28, 24],
       [30, 32, 34],
       [38, 21, 38],
       [25, 34, 37],
       [35, 30, 21],
       [22, 21, 21],
       [37, 30, 23]], dtype=int32)

In [7]:
#Average Temperature of each day for alll seven days

for i in range(len(data)):
    
    Days = data[i, :]
    mean_sale = np.mean(Days)
    
    print(f" Day {i+1} average temperature: {round(mean_sale)}")


 Day 1 average temperature: 29
 Day 2 average temperature: 32
 Day 3 average temperature: 32
 Day 4 average temperature: 32
 Day 5 average temperature: 29
 Day 6 average temperature: 21
 Day 7 average temperature: 30


Q3. Financial Analysis: You have a NumPy array representing the daily closing prices of a stock for a month. Calculate the monthly return, which is the percentage change from the first to the last day of the month.


In [8]:
#Daily Closing Prices for 30 days

closing_prices = np.random.randint(90,100, 30)
closing_prices

array([92, 93, 99, 93, 90, 98, 92, 97, 95, 91, 99, 96, 97, 96, 91, 90, 94,
       95, 93, 94, 92, 96, 90, 99, 98, 91, 99, 94, 94, 92], dtype=int32)

In [9]:
first_day_price = closing_prices[0]
last_day_price = closing_prices[-1]

monthly_return = ((last_day_price / first_day_price) - 1) * 100
print(f"The percentage monthly return is {monthly_return}%")

The percentage monthly return is 0.0%


Q4. Student Grades Analysis: You have a 2D NumPy array where each row represents a student and each column represents their grades in different subjects. Calculate the average grade for each student and the overall class average for each subject.


In [10]:
#2D Array with Grades 10 students

Students_Grades = np.random.randint(40,100, (10,5))
print(Students_Grades)

[[80 78 87 76 96]
 [65 88 55 94 44]
 [68 99 49 68 59]
 [77 73 83 58 55]
 [42 68 56 53 63]
 [44 54 66 61 76]
 [90 53 55 47 48]
 [90 41 54 62 95]
 [84 91 82 52 82]
 [96 58 54 75 79]]


In [11]:
#Average Grade of each student

for i in range(len(Students_Grades)):
    
    Students = Students_Grades[i, :]
    Avg_Grades = np.mean(Students)
    
    print(f" Student {i+1} average Grades: {Avg_Grades}")

 Student 1 average Grades: 83.4
 Student 2 average Grades: 69.2
 Student 3 average Grades: 68.6
 Student 4 average Grades: 69.2
 Student 5 average Grades: 56.4
 Student 6 average Grades: 60.2
 Student 7 average Grades: 58.6
 Student 8 average Grades: 68.4
 Student 9 average Grades: 78.2
 Student 10 average Grades: 72.4


In [12]:
#Overall Class average of each subject

for i in range(len(Students_Grades[0,:])):
    
    Subject = Students_Grades[i:, i]
    S_Avg_Grades = np.mean(Subject)
    
    print(f" Subject {i+1} average Grade: {round(S_Avg_Grades)}")

 Subject 1 average Grade: 74
 Subject 2 average Grade: 69
 Subject 3 average Grade: 62
 Subject 4 average Grade: 58
 Subject 5 average Grade: 74


Q5. Image Processing: You have a grayscale image represented as a 2D NumPy array of pixel intensities. Normalize the pixel values to a range of 0 to 1.


In [13]:

# 2D NumPy array 
image = np.random.randint(1,42, (10,10))

# Normalizing the pixel values to a range of 0 to 1 (Formula given by Chat-GPT)
min_val = np.min(image)
max_val = np.max(image)

normalized_image = (image - min_val) / (max_val - min_val)
normalized_image

array([[0.225, 0.05 , 0.925, 1.   , 0.1  , 0.725, 0.325, 0.95 , 0.825,
        0.775],
       [0.575, 0.275, 0.875, 0.9  , 0.225, 0.775, 0.95 , 0.825, 0.55 ,
        0.95 ],
       [0.9  , 0.7  , 0.625, 0.775, 0.55 , 0.425, 0.375, 0.8  , 0.8  ,
        0.225],
       [0.825, 1.   , 0.3  , 0.9  , 0.575, 0.55 , 0.275, 0.925, 0.375,
        0.175],
       [0.975, 0.925, 0.4  , 0.25 , 0.525, 0.35 , 0.05 , 0.8  , 0.325,
        0.35 ],
       [0.275, 0.025, 0.175, 0.05 , 0.675, 0.7  , 0.425, 0.525, 0.15 ,
        0.55 ],
       [0.5  , 0.175, 0.475, 0.3  , 0.6  , 0.375, 0.975, 0.925, 0.75 ,
        0.275],
       [0.4  , 0.15 , 0.55 , 0.1  , 0.125, 0.725, 0.125, 0.175, 0.525,
        0.225],
       [0.975, 0.55 , 0.8  , 0.45 , 0.075, 0.1  , 0.   , 0.925, 0.025,
        0.275],
       [0.075, 0.225, 0.475, 0.725, 0.375, 0.4  , 0.75 , 0.85 , 0.3  ,
        0.7  ]])

Q6. Population Growth Analysis: You have a NumPy array representing the population of a city over 10 years. Calculate the annual growth rate and identify the year with the highest growth.


In [14]:
population = np.array([1000, 1050, 1120, 1180, 1250, 1300, 1400, 1500, 1600, 1750])

# Annual growth rates
growth_rates = np.diff(population) / population[:-1] * 100

# Year with the highest growth
highest_growth = np.max(growth_rates)
highest_growth_year = np.argmax(growth_rates) + 1  

growth_rates = growth_rates.reshape(9,1)

print("Growth rate of each year")
print(np.round(growth_rates,1))
print(f"The Highest growth rate was {highest_growth} and the year was {highest_growth_year}")


Growth rate of each year
[[5. ]
 [6.7]
 [5.4]
 [5.9]
 [4. ]
 [7.7]
 [7.1]
 [6.7]
 [9.4]]
The Highest growth rate was 9.375 and the year was 9


Q7.Traffic Data Analysis: Given a 2D NumPy array where each row represents the number of vehicles passing through a checkpoint in different hours of the day over a week, calculate the total traffic for each day and the busiest hour of the week.


In [15]:
#Vehicles ranging from 50 to 500 and 7 rows for 7 days and 5 time frames (9AM, 12PM, 3PM, 6PM, 9PM)

traffic = np.random.randint(50, 500, (7,5))
traffic

array([[374, 313, 268,  93, 321],
       [ 91, 374, 322, 427, 262],
       [394, 184, 325, 152,  82],
       [ 60,  75, 398, 453, 271],
       [110, 315, 117, 184,  69],
       [145, 297, 445, 384, 298],
       [181, 271, 100, 421,  57]], dtype=int32)

In [16]:
#Total traffic for each day

for i in range(len(traffic)):
    total_traffic = np.sum(traffic[i, :])
    print(f"Day {i+1} total traffic {total_traffic}")

Day 1 total traffic 1369
Day 2 total traffic 1476
Day 3 total traffic 1137
Day 4 total traffic 1257
Day 5 total traffic 795
Day 6 total traffic 1569
Day 7 total traffic 1030


In [17]:
#Busiest hour of the week

busiest_hour_traffic = np.max(traffic)
busiest_hour = np.argmax(traffic) + 1


if busiest_hour in [1,6,11,16,21,26,31]:
     
    print(f" Busiest Hour was 9AM with {busiest_hour_traffic} vehicles passed" )

elif busiest_hour in [2,7,12,17,22,27,32]:
        print(f" Busiest Hour was 12PM with {busiest_hour_traffic} vehicles passed" )

elif busiest_hour in [3,8,13,18,23,28,33]:
        print(f" Busiest Hour was 3PM with {busiest_hour_traffic} vehicles passed" )

elif busiest_hour in [4,9,14,19,24,29,34]:
        print(f" Busiest Hour was 6PM with {busiest_hour_traffic} vehicles passed" )

elif busiest_hour in [5,10,15,20,25,30,35]:
        print(f" Busiest Hour was 9PM with {busiest_hour_traffic} vehicles passed" )
        


 Busiest Hour was 6PM with 453 vehicles passed


In [18]:
#Busiest hour of the week

busiest_hour_traffic = np.max(traffic)
busiest_hour = np.argmax(traffic) + 1

AM_9 = [1,6,11,16,21,26,31]
PM_12 = [2,7,12,17,22,27,32]
PM_3 = [3,8,13,18,23,28,33]
PM_6 = [4,9,14,19,24,29,34]
PM_9 = [5,10,15,20,25,30,35]

#For 9AM
if busiest_hour in AM_9:
    for i in AM_9:
           if i == busiest_hour:
                  day = AM_9.index(i) +1
     
    print(f"Busiest Hour was On day {day}, 9AM with {busiest_hour_traffic} vehicles passed" )

#For 12PM
elif busiest_hour in PM_12:
        for i in PM_12:
           if i == busiest_hour:
                  day = PM_12.index(i) +1
        print(f"Busiest Hour was On day {day}, 12PM with {busiest_hour_traffic} vehicles passed" )

#For 3PM
elif busiest_hour in PM_3:
        for i in PM_3:
           if i == busiest_hour:
                  day = PM_3.index(i) +1
        print(f"Busiest Hour was On day {day}, 3PM with {busiest_hour_traffic} vehicles passed" )

#For 6PM
elif busiest_hour in PM_6:
        for i in PM_6:
           if i == busiest_hour:
                  day = PM_6.index(i) +1
        print(f"Busiest Hour was On day {day}, 6PM with {busiest_hour_traffic} vehicles passed" )

#For 9PM
elif busiest_hour in PM_9:
        for i in PM_9:
           if i == busiest_hour:
                  day = PM_9.index(i) +1
        print(f"Busiest Hour was On day {day}, 9PM with {busiest_hour_traffic} vehicles passed" )
        


Busiest Hour was On day 4, 6PM with 453 vehicles passed


Q8. Product Inventory Management: You have a NumPy array representing the stock levels of different products in a warehouse. Reorder the products with stock levels below a threshold (e.g., 50 units).


In [19]:
#Creating a random stock of range 20-100 with 10 items
stock_levels = np.random.randint(20,100,10)

print(stock_levels)

products_to_reorder = stock_levels[stock_levels < 50]

# Print the products that need to be reordered
print(products_to_reorder)


[27 42 73 34 82 20 64 22 27 45]
[27 42 34 20 22 27 45]


Q9. Game Score Analysis: You have a NumPy array representing the scores of different players in a game over multiple rounds. Identify the player with the highest average score and the round with the highest total score.


In [20]:
# Creating Random game scores of 5 players in 3 rounds.

scores = np.random.randint(0,100, (5,3))
scores

array([[90, 66, 22],
       [28, 34, 25],
       [11, 76,  9],
       [80, 18, 21],
       [91, 42, 87]], dtype=int32)

In [21]:
#Calculating highest average_scores
average_scores = np.mean(scores, axis=1)

average_scores = np.reshape(average_scores, (5,1))
average_scores = np.round(average_scores)
average_scores

array([[59.],
       [29.],
       [32.],
       [40.],
       [73.]])

In [22]:
#Player with highest average score

player = np.argmax(average_scores) + 1
print(f"Player {player} has the highest average score")

Player 5 has the highest average score


In [23]:
#Total Scores each round
total_scores_per_round = np.sum(scores, axis=0)
total_scores_per_round

array([300, 236, 164])

In [24]:
#Round with the highest total scores

round = np.argmax(total_scores_per_round) + 1
print(f"Round {round} had the highest total scores")

Round 1 had the highest total scores


Q10. Financial Portfolio Analysis: You have a NumPy array representing the daily returns of different assets in a financial portfolio over a month. Calculate the portfolio's overall daily return, and identify the asset with the highest volatility.

In [26]:
# Array representing the daily returns of different assets over a month
daily_returns = np.random.random((30,5))
daily_returns

array([[0.64180603, 0.56566614, 0.58014531, 0.10054941, 0.39548366],
       [0.85844703, 0.22361914, 0.86040662, 0.56243947, 0.19049167],
       [0.01191932, 0.65118369, 0.51525658, 0.50117637, 0.43939686],
       [0.02827889, 0.9844519 , 0.17855821, 0.10745842, 0.58668139],
       [0.99353365, 0.59792112, 0.20248066, 0.70646158, 0.00267355],
       [0.32222774, 0.06588342, 0.31376304, 0.27501755, 0.27846587],
       [0.96649801, 0.91066255, 0.52308988, 0.15401399, 0.74329822],
       [0.45721978, 0.8103861 , 0.80789825, 0.53663433, 0.58316919],
       [0.92714659, 0.06906212, 0.98592479, 0.13086673, 0.48625653],
       [0.73093739, 0.19442171, 0.04245351, 0.78152002, 0.27593123],
       [0.36932475, 0.13566862, 0.94747918, 0.63069999, 0.97051148],
       [0.12194089, 0.191858  , 0.41407754, 0.81068987, 0.66962687],
       [0.85985694, 0.32434309, 0.3023862 , 0.42729033, 0.58539512],
       [0.07325946, 0.94677974, 0.5927385 , 0.36360494, 0.18001242],
       [0.83701339, 0.8956208 , 0.

In [29]:


# overall daily return for the portfolio
overall_daily_return = np.mean(daily_returns, axis=0)

# volatility (standard deviation) for each asset
volatility = np.std(daily_returns, axis=1)

# Identifying the asset with the highest volatility
highest_volatility_index = np.argmax(volatility)
highest_volatility = volatility[highest_volatility_index]

# Step 5: Print the results
print("Overall daily return of the portfolio:")
print(overall_daily_return)
print("\nAsset with the highest volatility: Asset {}".format(highest_volatility_index + 1))
print("Highest volatility (standard deviation of returns): {:.4f}".format(highest_volatility))


Overall daily return of the portfolio:
[0.561372   0.51286152 0.56103243 0.4640342  0.51316714]

Asset with the highest volatility: Asset 9
Highest volatility (standard deviation of returns): 0.3844


_________________________________________________________________________________________________________________________________________________
<Center>The End of Scenario Assignment </Center>