# **Muhammad Muzammil**

> Numpy Assignment
> 
> 26 September 2024

> **Q1. Create a 1D array, a 2D array, and a 3D array.**


In [1]:
import numpy as np

#1D
d1 = np.array([1,2,3,4,5])
d1

array([1, 2, 3, 4, 5])

In [2]:
#2D
d2 = np.array([[1,2,3], [3,4,5]])
d2

array([[1, 2, 3],
       [3, 4, 5]])

In [3]:
#3D
d3 = np.array([[ [1,2,3], [4,5,6], [7,8,9] ]])
d3


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

> **Q2. Perform slicing operations on arrays**

In [4]:
S1 = np.array([10,11,12,13,14,15,16])

S1[2:5]

array([12, 13, 14])

> **Q3. Perform basic arithmetic operations on arrays (addition, subtraction, multiplication, division).**

In [5]:
#Addition

A1 = np.array([2,4,6])

A2 = np.array([2,3,4])

Add = A1 + A2
Add

array([ 4,  7, 10])

In [6]:
#Subtraction

Sub = A1 - A2
Sub

array([0, 1, 2])

In [7]:
#Multiplication

Mul = A1 * A2
Mul

array([ 4, 12, 24])

In [8]:
#Division

Div = A1 / A2
Div

array([1.        , 1.33333333, 1.5       ])

**Array Creation and Manipulation**


**Q4. Create arrays using different functions: arange, linspace, zeros, ones, eye, random.**

In [9]:
#Creating Array directly

np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [10]:
#Creating Array from a list

arr = [1,3,5,7,9]
np.array(arr)

array([1, 3, 5, 7, 9])

In [12]:
# Creating Array from arange

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
# Creating Array from linspace (Evenly space 5 numbers from 0 to 1)

np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
#Zeros

np.zeros(3)

array([0., 0., 0.])

In [17]:
#Ones

np.ones(4)

array([1., 1., 1., 1.])

In [20]:
#eye (returns a 2D array with ones on the diagonal and zeros elsewhere.)

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
#Random

np.random.random((2,2))

array([[0.0555952 , 0.70583221],
       [0.69888355, 0.85100892]])

**Q5. Reshape an array.**

In [31]:
x = np.array([1,2,1,2,1,2,1,2])

z = x.reshape(4,2)
z

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

**Q6. Concatenate and split arrays.**

In [42]:
#Concatenate

A1 = np.array([2,4,6,8,10])

A2 = np.array([12,14,16,18,20])

x = np.concatenate((A1, A2))
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [52]:
#Spliting

np.split(x, 5)

[array([2, 4]),
 array([6, 8]),
 array([10, 12]),
 array([14, 16]),
 array([18, 20])]

**Statistical Operations**

**Q7. Compute mean, median, variance, and standard deviation of an array.**

In [35]:
#Mean
np.mean(A1)

np.float64(6.0)

In [36]:
#Median
np.median(A1)

np.float64(6.0)

In [41]:
#Variance
np.var(A1)

np.float64(8.0)

In [40]:
#Standard Deviation
np.std(A1)

np.float64(2.8284271247461903)

**Q8. Find the minimum and maximum values in an array along with their indices.**

In [55]:
#Maximum
A0 = np.array([1,5,8,50,12])

max_val = np.max(A0)
max_index = np.argmax(A0)

print(max_val)
print(max_index)

50
3


In [56]:
#Minimum
min_val = np.min(A0)
min_index = np.argmin(A0)

print(min_val)
print(min_index)

1
0


**Q9. Compute the sum and product of array elements.**

In [57]:
#Sum

np.sum(A0)

np.int64(76)

In [58]:
#Product

np.prod(A0)

np.int64(24000)

**Broadcasting**

**Q10. Demonstrate broadcasting with examples of different shapes of arrays.**

In [59]:
#Simple Broadcasting

B = np.array([1,2,3])
B + 10

array([11, 12, 13])

In [60]:
#2D array
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

#1D array
arr_1d = np.array([1, 2, 3, 4])

# Broadcasting 1D array to 2D array
arr_2d + arr_1d


array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [61]:
#Arrays with different shapes

#3x1 array
arr_3x1 = np.array([[1], [2], [3]])

#1x3 array
arr_1x3 = np.array([10, 20, 30])

# Broadcasting the two arrays
arr_3x1 * arr_1x3



array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

**Linear Algebra**

**Q11. Perform matrix multiplication.**


In [62]:
#Using dot

M1 = np.array([[1,2], [3,4]])
M2 = np.array([[5,6], [7,8]])

np.dot(M1,M2)

array([[19, 22],
       [43, 50]])

In [63]:
#Using Matmul

np.matmul(M1, M2)

array([[19, 22],
       [43, 50]])

**Q12. Compute the determinant, inverse, and eigenvalues of a matrix.**

In [65]:
# Determinant of the matrix

np.linalg.det(M1)

np.float64(-2.0000000000000004)

In [66]:
# Inverse of the matrix
np.linalg.inv(M1)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [67]:
# Eigenvalues of the matrix
np.linalg.eigvals(M1)

array([-0.37228132,  5.37228132])

**Q13. Solve a system of linear equations.**

In [68]:

#matrix A
A = np.array([[2, 1], [3, 4]])

# Constants vector b
b = np.array([5, 6])

# Solving for x (x and y)
solution = np.linalg.solve(A, b)
solution


array([ 2.8, -0.6])

**Advanced Indexing and Slicing**


**Q14. Use Boolean indexing to filter an array.**


In [69]:
#Condition
filterArr = np.array([12,34,65,23,86,45,83,21])

filterArr[filterArr>25]

array([34, 65, 86, 45, 83])

In [70]:
filterArr[filterArr % 2 == 0]

array([12, 34, 86])

**Q15. Use fancy indexing to select specific elements from an array.**

In [72]:
fancy_index = np.array([12,34,65,23,86,45,83,21])

#By Index Range
fancy_index[0:3]

array([12, 34, 65])

In [78]:
#By Specidic Indexes

fancy_index[[0,4,6]]

array([12, 86, 83])

In [84]:
#2D Array

fancy_index_2D = np.array([[12,24,36], [22,44,88], [33,66,99]])

fancy_index_2D

array([[12, 24, 36],
       [22, 44, 88],
       [33, 66, 99]])

In [86]:
#0 ka 1, 1 ka 0, 2 ka 2

fancy_index_2D[[0,1,2],[1,0,2]]


array([24, 22, 99])

**Q16. Perform advanced slicing operations.**


In [88]:
data = np.arange(1, 21) 
data 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [91]:
#Slicing with 2 Stops
slicing_1 = data[::2]
slicing_1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [95]:
data_2d = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12],
                    [13, 14, 15, 16]])

# Advanced slicing: Select the first two rows and the last two columns
data_2d[0:2, -2:]


array([[3, 4],
       [7, 8]])

In [96]:
# Advanced slicing: Select every second row and every second column
data_2d[::2, ::2]

array([[ 1,  3],
       [ 9, 11]])

**Random Sampling**

**Q17. Generate random numbers from different distributions.**

In [98]:
#Genereates 10 random number between 0 and 1
np.random.random(10)

array([0.99064983, 0.64648292, 0.72859107, 0.95150497, 0.04549807,
       0.73114134, 0.17421149, 0.10832458, 0.17810957, 0.55616792])

In [102]:
#Genereates random number with 2 rows and 3 columns

np.random.rand(2,3)

array([[0.6358785 , 0.11962746, 0.71655885],
       [0.56554608, 0.94254684, 0.51921732]])

In [112]:
#10 Random integers between 1 to 20 
np.random.randint(1,20,10)

array([ 5,  3, 11, 17, 13,  8,  1,  6, 13,  2], dtype=int32)

In [114]:
# 3 by 3 array Random integers between 1 to 20 
np.random.randint(1,20, (3,3))

array([[ 4,  7, 13],
       [ 1,  4, 11],
       [ 5, 19,  9]], dtype=int32)

**The End of Assignment**

**114 Code Snippets**

**Covered All Question**